### PR TITLE
Remove code causing settings page to pop up on install (issue #268)

### PR DESCRIPTION
**Pull request by sophieeng**

### CODE REVIEW

**Comment by OliverWang13** [comment]
Looks good! Do you think you could delete the identical code found in `events.js` as well?

**Review by OliverWang13 — CHANGES_REQUESTED** [review]
Looks good! Do you think you could delete the identical code found in `events.js` as well?

**Comment by SebastianZimmeck** [comment]
Do you agree with these changes, @sophieeng? If so, you can [push them to your issue-268 branch](https://stackoverflow.com/questions/16748115/how-to-modify-github-pull-request). If not, what do you suggest instead?

**Comment by OliverWang13** [comment]
Perfect, I'll merge the pull request and feel free to close issue #268

**Pull request merged**
