### PR TITLE
Issue 443, fixed github logout issue

### PR DESCRIPTION
**Pull request by OliverWang13**
This should all be dealt with.

On your end, can you check if two things are working:

1. Go to `https://global-privacy-control.glitch.me/`, the DOM signal and header should still be being sent.
2. Inspect the page and look at the cookies, is there a usprivacy string cookie with the value `1NYN`? (there should be)
3. Using the popup, opt back in to sales then reload the page.
4. The DOM signal and header should not be sent anymore.
5. The usprivacy string cookie should still be there but with `1NNN`
6. Navigate to `https://www.33across.com/`
7. In the cookies, there should be a cookie named `33x_nc` with the value `33Across+Optout`
8. If you opt in to that site, that cookie should be deleted
9. If you opt out of that site again, the cookie should reappear
10. Finally, try to replicate the github issue again and you should not be logged out

Please try to do these checks for both Chrome and Firefox

### CODE REVIEW

**Comment by OliverWang13** [comment]
CI tests were failing at first but I updated our tests to reflect the changes in the functions I made, as well as added some new test cases as well

**Comment by SebastianZimmeck** [comment]
@Mattm27 will review.

**Review by Mattm27 — CHANGES_REQUESTED** [review]
For Chrome, all checks for both ```https://global-privacy-control.glitch.me/``` and ```https://www.33across.com/``` look good and there is no longer a logout issue with Github. For Firefox, on ```https://global-privacy-control.glitch.me/``` after opting into sales and reloading page, DOM signal was still present (check 4) but with yellow thumbs up instead of blue. Other than that, all other checks for Firefox pass including those on ```https://www.33across.com/``` and there is no longer a logout issue with Github.

**Comment by OliverWang13** [comment]
This looks like it's due to a change on Firefox's end, so I think this is not an issue. Normally, by default, `navigator.globalPrivacyControl` is undefined, causing the red thumbs down, but it seems as though Firefox has changed their default to be so `navigator.globalPrivacyControl` is `False`, causing the yellow thumbs up. This might be something that should be changed with the [glitch site](https://global-privacy-control.glitch.me/), but should not be an issue for us.

**Pull request merged**
